// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDJC68spw3Z8ilzf7eYorObSeIi-lkmyOo",
    authDomain: "galabin-flutter---3c.firebaseapp.com",
    projectId: "galabin-flutter---3c",
    storageBucket: "galabin-flutter---3c.firebasestorage.app",
    messagingSenderId: "525631488555",
    appId: "1:525631488555:web:3006269c6b1ec6949da06e",
    measurementId: "G-3PLHNPXXEM"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuSWswOodqVDC4meu3Sk1a7LwtH5mN1co',
    appId: '1:525631488555:android:547656a1344f62819da06e',
    messagingSenderId: '525631488555',
    projectId: 'galabin-flutter---3c',
    storageBucket: 'galabin-flutter---3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wSA2xq1GvIh6cPUR2KV4WMC7OsdMBe8',
    appId: '1:525631488555:ios:208a11504e2a700b9da06e',
    messagingSenderId: '525631488555',
    projectId: 'galabin-flutter---3c',
    storageBucket: 'galabin-flutter---3c.firebasestorage.app',
    androidClientId: '525631488555-tlf3bn2jlthie6rv0blo4i7a3ql7j5t3.apps.googleusercontent.com',
    iosClientId: '525631488555-h88b41qughnlccpvur0os9915u306tk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileapplication',
  );
}
